 let str = [
    {
      "login": "mkruijt",
      "id": 7113309,
      "node_id": "MDQ6VXNlcjcxMTMzMDk=",
      "avatar_url": "https://avatars2.githubusercontent.com/u/7113309?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/mkruijt",
      "html_url": "https://github.com/mkruijt",
      "followers_url": "https://api.github.com/users/mkruijt/followers",
      "following_url": "https://api.github.com/users/mkruijt/following{/other_user}",
      "gists_url": "https://api.github.com/users/mkruijt/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/mkruijt/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/mkruijt/subscriptions",
      "organizations_url": "https://api.github.com/users/mkruijt/orgs",
      "repos_url": "https://api.github.com/users/mkruijt/repos",
      "events_url": "https://api.github.com/users/mkruijt/events{/privacy}",
      "received_events_url": "https://api.github.com/users/mkruijt/received_events",
      "type": "User",
      "site_admin": false,
      "contributions": 251
    },
    {
      "login": "remarcmij",
      "id": 2788771,
      "node_id": "MDQ6VXNlcjI3ODg3NzE=",
      "avatar_url": "https://avatars0.githubusercontent.com/u/2788771?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/remarcmij",
      "html_url": "https://github.com/remarcmij",
      "followers_url": "https://api.github.com/users/remarcmij/followers",
      "following_url": "https://api.github.com/users/remarcmij/following{/other_user}",
      "gists_url": "https://api.github.com/users/remarcmij/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/remarcmij/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/remarcmij/subscriptions",
      "organizations_url": "https://api.github.com/users/remarcmij/orgs",
      "repos_url": "https://api.github.com/users/remarcmij/repos",
      "events_url": "https://api.github.com/users/remarcmij/events{/privacy}",
      "received_events_url": "https://api.github.com/users/remarcmij/received_events",
      "type": "User",
      "site_admin": false,
      "contributions": 100
    },
    {
      "login": "Razpudding",
      "id": 8708858,
      "node_id": "MDQ6VXNlcjg3MDg4NTg=",
      "avatar_url": "https://avatars3.githubusercontent.com/u/8708858?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Razpudding",
      "html_url": "https://github.com/Razpudding",
      "followers_url": "https://api.github.com/users/Razpudding/followers",
      "following_url": "https://api.github.com/users/Razpudding/following{/other_user}",
      "gists_url": "https://api.github.com/users/Razpudding/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Razpudding/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Razpudding/subscriptions",
      "organizations_url": "https://api.github.com/users/Razpudding/orgs",
      "repos_url": "https://api.github.com/users/Razpudding/repos",
      "events_url": "https://api.github.com/users/Razpudding/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Razpudding/received_events",
      "type": "User",
      "site_admin": false,
      "contributions": 43
    },
    {
      "login": "joostlubach",
      "id": 969026,
      "node_id": "MDQ6VXNlcjk2OTAyNg==",
      "avatar_url": "https://avatars3.githubusercontent.com/u/969026?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/joostlubach",
      "html_url": "https://github.com/joostlubach",
      "followers_url": "https://api.github.com/users/joostlubach/followers",
      "following_url": "https://api.github.com/users/joostlubach/following{/other_user}",
      "gists_url": "https://api.github.com/users/joostlubach/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/joostlubach/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/joostlubach/subscriptions",
      "organizations_url": "https://api.github.com/users/joostlubach/orgs",
      "repos_url": "https://api.github.com/users/joostlubach/repos",
      "events_url": "https://api.github.com/users/joostlubach/events{/privacy}",
      "received_events_url": "https://api.github.com/users/joostlubach/received_events",
      "type": "User",
      "site_admin": false,
      "contributions": 14
    },
    {
      "login": "eidosam",
      "id": 17527017,
      "node_id": "MDQ6VXNlcjE3NTI3MDE3",
      "avatar_url": "https://avatars2.githubusercontent.com/u/17527017?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/eidosam",
      "html_url": "https://github.com/eidosam",
      "followers_url": "https://api.github.com/users/eidosam/followers",
      "following_url": "https://api.github.com/users/eidosam/following{/other_user}",
      "gists_url": "https://api.github.com/users/eidosam/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/eidosam/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/eidosam/subscriptions",
      "organizations_url": "https://api.github.com/users/eidosam/orgs",
      "repos_url": "https://api.github.com/users/eidosam/repos",
      "events_url": "https://api.github.com/users/eidosam/events{/privacy}",
      "received_events_url": "https://api.github.com/users/eidosam/received_events",
      "type": "User",
      "site_admin": false,
      "contributions": 13
    },
    {
      "login": "M3kH",
      "id": 651290,
      "node_id": "MDQ6VXNlcjY1MTI5MA==",
      "avatar_url": "https://avatars0.githubusercontent.com/u/651290?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/M3kH",
      "html_url": "https://github.com/M3kH",
      "followers_url": "https://api.github.com/users/M3kH/followers",
      "following_url": "https://api.github.com/users/M3kH/following{/other_user}",
      "gists_url": "https://api.github.com/users/M3kH/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/M3kH/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/M3kH/subscriptions",
      "organizations_url": "https://api.github.com/users/M3kH/orgs",
      "repos_url": "https://api.github.com/users/M3kH/repos",
      "events_url": "https://api.github.com/users/M3kH/events{/privacy}",
      "received_events_url": "https://api.github.com/users/M3kH/received_events",
      "type": "User",
      "site_admin": false,
      "contributions": 9
    },
    {
      "login": "tkaria",
      "id": 1047135,
      "node_id": "MDQ6VXNlcjEwNDcxMzU=",
      "avatar_url": "https://avatars0.githubusercontent.com/u/1047135?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/tkaria",
      "html_url": "https://github.com/tkaria",
      "followers_url": "https://api.github.com/users/tkaria/followers",
      "following_url": "https://api.github.com/users/tkaria/following{/other_user}",
      "gists_url": "https://api.github.com/users/tkaria/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/tkaria/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/tkaria/subscriptions",
      "organizations_url": "https://api.github.com/users/tkaria/orgs",
      "repos_url": "https://api.github.com/users/tkaria/repos",
      "events_url": "https://api.github.com/users/tkaria/events{/privacy}",
      "received_events_url": "https://api.github.com/users/tkaria/received_events",
      "type": "User",
      "site_admin": false,
      "contributions": 5
    },
    {
      "login": "gijscor",
      "id": 15912395,
      "node_id": "MDQ6VXNlcjE1OTEyMzk1",
      "avatar_url": "https://avatars0.githubusercontent.com/u/15912395?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/gijscor",
      "html_url": "https://github.com/gijscor",
      "followers_url": "https://api.github.com/users/gijscor/followers",
      "following_url": "https://api.github.com/users/gijscor/following{/other_user}",
      "gists_url": "https://api.github.com/users/gijscor/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/gijscor/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/gijscor/subscriptions",
      "organizations_url": "https://api.github.com/users/gijscor/orgs",
      "repos_url": "https://api.github.com/users/gijscor/repos",
      "events_url": "https://api.github.com/users/gijscor/events{/privacy}",
      "received_events_url": "https://api.github.com/users/gijscor/received_events",
      "type": "User",
      "site_admin": false,
      "contributions": 4
    },
    {
      "login": "onnlucky",
      "id": 45293,
      "node_id": "MDQ6VXNlcjQ1Mjkz",
      "avatar_url": "https://avatars3.githubusercontent.com/u/45293?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/onnlucky",
      "html_url": "https://github.com/onnlucky",
      "followers_url": "https://api.github.com/users/onnlucky/followers",
      "following_url": "https://api.github.com/users/onnlucky/following{/other_user}",
      "gists_url": "https://api.github.com/users/onnlucky/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/onnlucky/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/onnlucky/subscriptions",
      "organizations_url": "https://api.github.com/users/onnlucky/orgs",
      "repos_url": "https://api.github.com/users/onnlucky/repos",
      "events_url": "https://api.github.com/users/onnlucky/events{/privacy}",
      "received_events_url": "https://api.github.com/users/onnlucky/received_events",
      "type": "User",
      "site_admin": false,
      "contributions": 4
    },
    {
      "login": "Hx66",
      "id": 22626039,
      "node_id": "MDQ6VXNlcjIyNjI2MDM5",
      "avatar_url": "https://avatars3.githubusercontent.com/u/22626039?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Hx66",
      "html_url": "https://github.com/Hx66",
      "followers_url": "https://api.github.com/users/Hx66/followers",
      "following_url": "https://api.github.com/users/Hx66/following{/other_user}",
      "gists_url": "https://api.github.com/users/Hx66/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Hx66/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Hx66/subscriptions",
      "organizations_url": "https://api.github.com/users/Hx66/orgs",
      "repos_url": "https://api.github.com/users/Hx66/repos",
      "events_url": "https://api.github.com/users/Hx66/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Hx66/received_events",
      "type": "User",
      "site_admin": false,
      "contributions": 3
    },
    {
      "login": "erols",
      "id": 658656,
      "node_id": "MDQ6VXNlcjY1ODY1Ng==",
      "avatar_url": "https://avatars3.githubusercontent.com/u/658656?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/erols",
      "html_url": "https://github.com/erols",
      "followers_url": "https://api.github.com/users/erols/followers",
      "following_url": "https://api.github.com/users/erols/following{/other_user}",
      "gists_url": "https://api.github.com/users/erols/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/erols/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/erols/subscriptions",
      "organizations_url": "https://api.github.com/users/erols/orgs",
      "repos_url": "https://api.github.com/users/erols/repos",
      "events_url": "https://api.github.com/users/erols/events{/privacy}",
      "received_events_url": "https://api.github.com/users/erols/received_events",
      "type": "User",
      "site_admin": false,
      "contributions": 3
    },
    {
      "login": "LaurensRietveld",
      "id": 988347,
      "node_id": "MDQ6VXNlcjk4ODM0Nw==",
      "avatar_url": "https://avatars3.githubusercontent.com/u/988347?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/LaurensRietveld",
      "html_url": "https://github.com/LaurensRietveld",
      "followers_url": "https://api.github.com/users/LaurensRietveld/followers",
      "following_url": "https://api.github.com/users/LaurensRietveld/following{/other_user}",
      "gists_url": "https://api.github.com/users/LaurensRietveld/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/LaurensRietveld/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/LaurensRietveld/subscriptions",
      "organizations_url": "https://api.github.com/users/LaurensRietveld/orgs",
      "repos_url": "https://api.github.com/users/LaurensRietveld/repos",
      "events_url": "https://api.github.com/users/LaurensRietveld/events{/privacy}",
      "received_events_url": "https://api.github.com/users/LaurensRietveld/received_events",
      "type": "User",
      "site_admin": false,
      "contributions": 3
    },
    {
      "login": "daanaerts",
      "id": 6762913,
      "node_id": "MDQ6VXNlcjY3NjI5MTM=",
      "avatar_url": "https://avatars0.githubusercontent.com/u/6762913?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/daanaerts",
      "html_url": "https://github.com/daanaerts",
      "followers_url": "https://api.github.com/users/daanaerts/followers",
      "following_url": "https://api.github.com/users/daanaerts/following{/other_user}",
      "gists_url": "https://api.github.com/users/daanaerts/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/daanaerts/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/daanaerts/subscriptions",
      "organizations_url": "https://api.github.com/users/daanaerts/orgs",
      "repos_url": "https://api.github.com/users/daanaerts/repos",
      "events_url": "https://api.github.com/users/daanaerts/events{/privacy}",
      "received_events_url": "https://api.github.com/users/daanaerts/received_events",
      "type": "User",
      "site_admin": false,
      "contributions": 2
    },
    {
      "login": "Kemirdin",
      "id": 33654086,
      "node_id": "MDQ6VXNlcjMzNjU0MDg2",
      "avatar_url": "https://avatars2.githubusercontent.com/u/33654086?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Kemirdin",
      "html_url": "https://github.com/Kemirdin",
      "followers_url": "https://api.github.com/users/Kemirdin/followers",
      "following_url": "https://api.github.com/users/Kemirdin/following{/other_user}",
      "gists_url": "https://api.github.com/users/Kemirdin/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Kemirdin/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Kemirdin/subscriptions",
      "organizations_url": "https://api.github.com/users/Kemirdin/orgs",
      "repos_url": "https://api.github.com/users/Kemirdin/repos",
      "events_url": "https://api.github.com/users/Kemirdin/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Kemirdin/received_events",
      "type": "User",
      "site_admin": false,
      "contributions": 2
    },
    {
      "login": "ChrisOwen101",
      "id": 5181870,
      "node_id": "MDQ6VXNlcjUxODE4NzA=",
      "avatar_url": "https://avatars2.githubusercontent.com/u/5181870?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/ChrisOwen101",
      "html_url": "https://github.com/ChrisOwen101",
      "followers_url": "https://api.github.com/users/ChrisOwen101/followers",
      "following_url": "https://api.github.com/users/ChrisOwen101/following{/other_user}",
      "gists_url": "https://api.github.com/users/ChrisOwen101/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/ChrisOwen101/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/ChrisOwen101/subscriptions",
      "organizations_url": "https://api.github.com/users/ChrisOwen101/orgs",
      "repos_url": "https://api.github.com/users/ChrisOwen101/repos",
      "events_url": "https://api.github.com/users/ChrisOwen101/events{/privacy}",
      "received_events_url": "https://api.github.com/users/ChrisOwen101/received_events",
      "type": "User",
      "site_admin": false,
      "contributions": 1
    },
    {
      "login": "jasongwartz",
      "id": 10981911,
      "node_id": "MDQ6VXNlcjEwOTgxOTEx",
      "avatar_url": "https://avatars1.githubusercontent.com/u/10981911?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jasongwartz",
      "html_url": "https://github.com/jasongwartz",
      "followers_url": "https://api.github.com/users/jasongwartz/followers",
      "following_url": "https://api.github.com/users/jasongwartz/following{/other_user}",
      "gists_url": "https://api.github.com/users/jasongwartz/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jasongwartz/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jasongwartz/subscriptions",
      "organizations_url": "https://api.github.com/users/jasongwartz/orgs",
      "repos_url": "https://api.github.com/users/jasongwartz/repos",
      "events_url": "https://api.github.com/users/jasongwartz/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jasongwartz/received_events",
      "type": "User",
      "site_admin": false,
      "contributions": 1
    },
    {
      "login": "malnajar",
      "id": 32513012,
      "node_id": "MDQ6VXNlcjMyNTEzMDEy",
      "avatar_url": "https://avatars0.githubusercontent.com/u/32513012?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/malnajar",
      "html_url": "https://github.com/malnajar",
      "followers_url": "https://api.github.com/users/malnajar/followers",
      "following_url": "https://api.github.com/users/malnajar/following{/other_user}",
      "gists_url": "https://api.github.com/users/malnajar/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/malnajar/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/malnajar/subscriptions",
      "organizations_url": "https://api.github.com/users/malnajar/orgs",
      "repos_url": "https://api.github.com/users/malnajar/repos",
      "events_url": "https://api.github.com/users/malnajar/events{/privacy}",
      "received_events_url": "https://api.github.com/users/malnajar/received_events",
      "type": "User",
      "site_admin": false,
      "contributions": 1
    },
    {
      "login": "wouterkleijn",
      "id": 37488847,
      "node_id": "MDQ6VXNlcjM3NDg4ODQ3",
      "avatar_url": "https://avatars1.githubusercontent.com/u/37488847?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/wouterkleijn",
      "html_url": "https://github.com/wouterkleijn",
      "followers_url": "https://api.github.com/users/wouterkleijn/followers",
      "following_url": "https://api.github.com/users/wouterkleijn/following{/other_user}",
      "gists_url": "https://api.github.com/users/wouterkleijn/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/wouterkleijn/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/wouterkleijn/subscriptions",
      "organizations_url": "https://api.github.com/users/wouterkleijn/orgs",
      "repos_url": "https://api.github.com/users/wouterkleijn/repos",
      "events_url": "https://api.github.com/users/wouterkleijn/events{/privacy}",
      "received_events_url": "https://api.github.com/users/wouterkleijn/received_events",
      "type": "User",
      "site_admin": false,
      "contributions": 1
    },
    {
      "login": "itemah26",
      "id": 30556626,
      "node_id": "MDQ6VXNlcjMwNTU2NjI2",
      "avatar_url": "https://avatars1.githubusercontent.com/u/30556626?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/itemah26",
      "html_url": "https://github.com/itemah26",
      "followers_url": "https://api.github.com/users/itemah26/followers",
      "following_url": "https://api.github.com/users/itemah26/following{/other_user}",
      "gists_url": "https://api.github.com/users/itemah26/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/itemah26/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/itemah26/subscriptions",
      "organizations_url": "https://api.github.com/users/itemah26/orgs",
      "repos_url": "https://api.github.com/users/itemah26/repos",
      "events_url": "https://api.github.com/users/itemah26/events{/privacy}",
      "received_events_url": "https://api.github.com/users/itemah26/received_events",
      "type": "User",
      "site_admin": false,
      "contributions": 1
    }
  ]


let a = new Object(str);

let b = a.map(x => x.login)
  console.log(b)